# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: dotnet-biuld

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 11 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checar o repositório
      uses: actions/checkout@v2  # Usando uma action pré-existente para fazer o checkout do código